language: bash

git:
  depth: 1

before_script:
  - wget https://svn.reactos.org/amine/RosBEBinFull.tar.gz -O RosBE.tar.gz
  - tar -xzf RosBE.tar.gz
  - echo 'mkdir ../Build && cd ../Build && $TRAVIS_BUILD_DIR/configure.sh && cd reactos && ninja -k 0 && ninja usbhub' > tmp_file

script:
  - ./RosBEBinFull/RosBE.sh < tmp_file
  - curl --upload-file /home/travis/build/nkrapivin/reactos/Build/reactos/drivers/usb/usbhub_new/usbhub.sys https://transfer.sh/usbhub.sys
